# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pms_09/Codes/TeoriaJuegos/Fundamento-de-Teoria-de-Juegos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pms_09/Codes/TeoriaJuegos/Fundamento-de-Teoria-de-Juegos/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pms_09/Codes/TeoriaJuegos/Fundamento-de-Teoria-de-Juegos/build/CMakeFiles /home/pms_09/Codes/TeoriaJuegos/Fundamento-de-Teoria-de-Juegos/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pms_09/Codes/TeoriaJuegos/Fundamento-de-Teoria-de-Juegos/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MOTOR

# Build rule for target.
MOTOR: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MOTOR
.PHONY : MOTOR

# fast build rule for target.
MOTOR/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/build
.PHONY : MOTOR/fast

Motor/Error.o: Motor/Error.cpp.o
.PHONY : Motor/Error.o

# target to build an object file
Motor/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/Error.cpp.o
.PHONY : Motor/Error.cpp.o

Motor/Error.i: Motor/Error.cpp.i
.PHONY : Motor/Error.i

# target to preprocess a source file
Motor/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/Error.cpp.i
.PHONY : Motor/Error.cpp.i

Motor/Error.s: Motor/Error.cpp.s
.PHONY : Motor/Error.s

# target to generate assembly for a file
Motor/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/Error.cpp.s
.PHONY : Motor/Error.cpp.s

Motor/HLSLProgram.o: Motor/HLSLProgram.cpp.o
.PHONY : Motor/HLSLProgram.o

# target to build an object file
Motor/HLSLProgram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/HLSLProgram.cpp.o
.PHONY : Motor/HLSLProgram.cpp.o

Motor/HLSLProgram.i: Motor/HLSLProgram.cpp.i
.PHONY : Motor/HLSLProgram.i

# target to preprocess a source file
Motor/HLSLProgram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/HLSLProgram.cpp.i
.PHONY : Motor/HLSLProgram.cpp.i

Motor/HLSLProgram.s: Motor/HLSLProgram.cpp.s
.PHONY : Motor/HLSLProgram.s

# target to generate assembly for a file
Motor/HLSLProgram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/HLSLProgram.cpp.s
.PHONY : Motor/HLSLProgram.cpp.s

Motor/MainGame.o: Motor/MainGame.cpp.o
.PHONY : Motor/MainGame.o

# target to build an object file
Motor/MainGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/MainGame.cpp.o
.PHONY : Motor/MainGame.cpp.o

Motor/MainGame.i: Motor/MainGame.cpp.i
.PHONY : Motor/MainGame.i

# target to preprocess a source file
Motor/MainGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/MainGame.cpp.i
.PHONY : Motor/MainGame.cpp.i

Motor/MainGame.s: Motor/MainGame.cpp.s
.PHONY : Motor/MainGame.s

# target to generate assembly for a file
Motor/MainGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/MainGame.cpp.s
.PHONY : Motor/MainGame.cpp.s

Motor/Sprite.o: Motor/Sprite.cpp.o
.PHONY : Motor/Sprite.o

# target to build an object file
Motor/Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/Sprite.cpp.o
.PHONY : Motor/Sprite.cpp.o

Motor/Sprite.i: Motor/Sprite.cpp.i
.PHONY : Motor/Sprite.i

# target to preprocess a source file
Motor/Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/Sprite.cpp.i
.PHONY : Motor/Sprite.cpp.i

Motor/Sprite.s: Motor/Sprite.cpp.s
.PHONY : Motor/Sprite.s

# target to generate assembly for a file
Motor/Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/Sprite.cpp.s
.PHONY : Motor/Sprite.cpp.s

Motor/main.o: Motor/main.cpp.o
.PHONY : Motor/main.o

# target to build an object file
Motor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/main.cpp.o
.PHONY : Motor/main.cpp.o

Motor/main.i: Motor/main.cpp.i
.PHONY : Motor/main.i

# target to preprocess a source file
Motor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/main.cpp.i
.PHONY : Motor/main.cpp.i

Motor/main.s: Motor/main.cpp.s
.PHONY : Motor/main.s

# target to generate assembly for a file
Motor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MOTOR.dir/build.make CMakeFiles/MOTOR.dir/Motor/main.cpp.s
.PHONY : Motor/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MOTOR"
	@echo "... Motor/Error.o"
	@echo "... Motor/Error.i"
	@echo "... Motor/Error.s"
	@echo "... Motor/HLSLProgram.o"
	@echo "... Motor/HLSLProgram.i"
	@echo "... Motor/HLSLProgram.s"
	@echo "... Motor/MainGame.o"
	@echo "... Motor/MainGame.i"
	@echo "... Motor/MainGame.s"
	@echo "... Motor/Sprite.o"
	@echo "... Motor/Sprite.i"
	@echo "... Motor/Sprite.s"
	@echo "... Motor/main.o"
	@echo "... Motor/main.i"
	@echo "... Motor/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

